"""
Django settings for private_diary project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yh%7vfbn=v6mq(=fsy*2+4!3wn21a0i*jnpt=1bs*#%7aocgh6'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'diary.apps.DiaryConfig',
    'accounts.apps.AccountsConfig',

    'django.contrib.sites',
    'allauth',
    'allauth.account',

    'django_ses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'private_diary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'private_diary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': 'private_diary',
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ja'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# 静的ファイル保存場所指定(CSSやIMGなど)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

# # ロギング設定
# LOGGING = {
#     'version': 1, # 1固定
#     'disable_existing_loggers': False, # 既存のロガーを無効化する設定
#
#     # ロガーの設定
#     'loggers': {
#         # Djangoが利用するロガー
#         'django': {
#             'handlers': ['console'],
#             'level': 'INFO',
#         },
#         # diaryアプリケーションが利用するロガー
#         'diary': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
#
#     # ハンドラの設定
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler', # StreamHandlerはコンソールへ出力するハンドラ
#             'formatter': 'dev'
#         },
#     },
#
#     # フォーマッタの設定。ログをタブ区切り出力するように設定
#     'formatters': {
#         'dev': {
#             'format': '\t'.join([
#                 '%(asctime)s',
#                 '[%(levelname)s]',
#                 '%(pathname)s(Line:%(lineno)d)',
#                 '%(message)s'
#             ])
#         },
#     }
# }

# base.htmlの{{ message.tags }}箇所に下記の設定がメッセージレベルに応じて反映される
# 例えばメッセージレベルがERRORであれば「<li class="alert alert-danger>メッセージ</li>」としてhtml出力されBootstrapのalertクラスが適用されます"
MESSAGE_TAGS = {
    messages.ERROR: 'alert alert-danger',
    messages.WARNING: 'alert alert-warning',
    messages.SUCCESS: 'alert alert-success',
    messages.INFO: 'alert alert-info',
}

# カスタムユーザーモデルを設定
AUTH_USER_MODEL = 'accounts.CustomUser'

# django-allauthで利用するdjango.contrib.sitesを使うためにサイト識別用IDを設定
SITE_ID = 1

# 認証バックエンド(認証をテストするクラス)を2つ設定。AUTHENTICATION_BACKENDSリストに設定した認証バックエンドを順に認証できまるで繰り返す
# ModelBackendを削除すると管理サイトもメールアドレス認証となるが画面上はユーザー名のラベルのままとなり修正に手間もかかるため管理サイトはユーザー名認証のままとしている
AUTHENTICATION_BACKENDS = (
    # 一般ユーザー用(メールアドレス認証）
    'allauth.account.auth_backends.AuthenticationBackend',
    # 管理サイト用(ユーザー名認証)
    'django.contrib.auth.backends.ModelBackend',
)

# メールアドレス認証に変更する設定
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False

# サインアップにメールアドレス確認をはさむよう設定。
# 「ユーザー登録(仮登録)」→「メール送信」→「メール上のリンクをクリック」→「ユーザー登録(本登録)」の流れ
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True

# ログイン後の遷移先(日記一覧)を設定
LOGIN_REDIRECT_URL = 'diary:diary_list'
# ログアウト後の遷移先を設定
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# ログアウトリンクのクリック1回でログアウトする設定
# django-allauthのデフォルトのログアウト挙動ではログアウトボタンクリック後にログアウト画面が表示され再度ログアウトボタンを押させる動きとなるため即ログアウトできるようにする
ACCOUNT_LOGOUT_ON_GET = True

# メディアファイル(画像)の配信URL設定
MEDIA_URL = '/media/'

# バックアップ保存先
BACKUP_PATH = 'backup/'
# バックアップファイル保持数
NUM_SAVED_BACKUP = 30

